databases:
  - name: joai_db1
    databaseName: joai_db1
    user: joai_user1
    plan: free # Free tier: 1 GB storage, expires after 90 days
    #ipAllowList: [] # Allow connections from any IP

services:
  - type: web
    name: joai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_CONNECTION
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: joai-db1
          property: connectionString
      - key: DB_URI_INTERNAL
        fromDatabase:
          name: joai-db1
          property: connectionString
  - type: pserv
    name: joai-db1
    runtime: postgresql
    ipAllowList: []  # Only accessible by other services in this project