databases:
  - name: joai_db1
    databaseName: joai_db1
    user: joai_user1
    password: 1Rim6AMqEOb0ZlApcFh8Ujrwt0ximlWN
    port: 5432
    host: dpg-d4acsls9c44c73e79or0-a
    plan: free # Free tier: 1 GB storage, expires after 90 days
    ipAllowList: [] # Allow connections from any IP

services:
  - type: web
    name: joai
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_CONNECTION
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: joai-db
          property: connectionString
  - type: pserv
    name: joai-db
    runtime: postgresql
    ipAllowList: []  # Only accessible by other services in this project